version: 2

models:
  - name: cuong_fact_orders
    description: Order transaction fact table
    columns:
      - name: order_id
        description: Order ID
        tests: [not_null]  # bỏ unique nếu dùng SCD2

      - name: order_date
        description: Order date
        tests: [not_null]

      - name: product_id
        description: Product ID
        tests: [not_null]

      - name: city_id
        description: City ID
        tests: []  # bỏ not_null nếu có NULL

      - name: cust_id
        description: Customer ID
        tests: [not_null]

      - name: sales_pers_id
        description: Salesperson ID
        tests: []  # bỏ not_null nếu NULL hợp lệ

      - name: quantity
        description: Quantity of product ordered
        tests: []

      - name: gross_sales
        description: Gross sales amount (total)
        tests: []

