name: dbt CI (Dev)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-oracle
        run: |
          python -m pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT profile
        run: |
          mkdir -p /usr/app/.dbt
          echo "$DBT_PROFILES_YML" > /usr/app/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      - name: Install dbt dependencies
        run: |
          cd oracle_project
          dbt deps --profiles-dir /usr/app/.dbt

      - name: Compile dbt models
        run: |
          cd oracle_project
          dbt compile --target dev --profiles-dir /usr/app/.dbt

      - name: Run dbt models
        run: |
          cd oracle_project
          dbt run --target dev --profiles-dir /usr/app/.dbt

      - name: Run dbt tests
        run: |
          cd oracle_project
          dbt test --target dev --profiles-dir /usr/app/.dbt
