name: dbt CD (Deploy to prod)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # ví dụ: v1.0.0

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-oracle
        run: |
          pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT prod profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML_PROD" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML_PROD: ${{ secrets.DBT_PROFILES_YML_PROD }}

      - name: Install dbt packages
        run: dbt deps --project-dir oracle_project --profiles-dir ~/.dbt

      - name: Run DBT models (prod)
        run: dbt run --project-dir oracle_project --target prod --profiles-dir ~/.dbt

      - name: Run DBT tests (prod)
        run: dbt test --project-dir oracle_project --target prod --profiles-dir ~/.dbt
