name: dbt CD (Deploy to Prod)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-oracle
        run: |
          python -m pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT prod profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML_PROD" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML_PROD: ${{ secrets.DBT_PROFILES_YML_PROD }}

      - name: Deploy to prod
        run: |
          cd oracle_project
          dbt deps
          dbt run --target prod
          dbt test --target prod
