name: dbt CI (Dev)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-oracle
        run: |
          python -m pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      - name: Install dbt dependencies
        run: dbt deps

      - name: Compile dbt models
        run: dbt compile --target dev

      - name: Run dbt models
        run: dbt run --target dev

      - name: Run dbt tests
        run: dbt test --target dev
