name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt Oracle adapter
        run: |
          pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT profile
        run: |
          mkdir -p /usr/app/.dbt
          echo "$DBT_PROFILES_YML" > /usr/app/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      - name: Install dbt packages
        run: dbt deps --project-dir oracle_project --profiles-dir /usr/app/.dbt

      - name: Compile DBT models
        run: dbt compile --project-dir oracle_project --target dev --profiles-dir /usr/app/.dbt

      - name: Run DBT models
        run: dbt run --project-dir oracle_project --target dev --profiles-dir /usr/app/.dbt

      - name: Run DBT tests
        run: dbt test --project-dir oracle_project --target dev --profiles-dir /usr/app/.dbt
