name: dbt CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt-oracle
        run: |
          pip install --upgrade pip
          pip install dbt-oracle

      - name: Set up DBT dev profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}

      - name: Install dbt packages
        run: dbt deps --project-dir oracle_project --profiles-dir ~/.dbt

      - name: Compile DBT models
        run: dbt compile --project-dir oracle_project --target dev --profiles-dir ~/.dbt

      - name: Run DBT models (dev)
        run: dbt run --project-dir oracle_project --target dev --profiles-dir ~/.dbt

      - name: Run DBT tests (dev)
        run: dbt test --project-dir oracle_project --target dev --profiles-dir ~/.dbt
