name: dbt CD (Deploy to Prod)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  dbt-deploy:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Check Python version
        run: |
          & "C:\Program Files\Python311\python.exe" --version

      - name: Install dbt-oracle
        run: |
          & "C:\Program Files\Python311\python.exe" -m pip install --upgrade pip
          & "C:\Program Files\Python311\python.exe" -m pip install dbt-oracle

      - name: Set up DBT prod profile
        run: |
          New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.dbt
          $env:DBT_PROFILES_YML_PROD | Out-File -Encoding ascii -FilePath $env:USERPROFILE\.dbt\profiles.yml
        env:
          DBT_PROFILES_YML_PROD: ${{ secrets.DBT_PROFILES_YML_PROD }}

      - name: Install dbt dependencies
        run: |
          & "C:\Program Files\Python311\Scripts\dbt.exe" deps

      - name: Run dbt models (prod)
        run: |
          & "C:\Program Files\Python311\Scripts\dbt.exe" run --target prod

      - name: Run dbt tests (prod)
        run: |
          & "C:\Program Files\Python311\Scripts\dbt.exe" test --target prod
